name = "Crispy"
profile-picture = "GitHub"
bio = "I make games and devlogs on Youtube. Huge fan of Rust and Bevy!"
sponsor = "https://ko-fi.com/crispygames"
github = "0crispy"
discord = "Crispy#5999"
discord-userid = "581747346329829376"
twitter = "abverse_dev"
website = "https://www.youtube.com/@crispy_dev"
