name = "Aceeri"
profile-picture = "GitHub"
bio = "Average Rust and game enjoyer"
github = "aceeri"
discord = "Aceeri#8491"
discord-userid = "85854114684092416"
itch-io = "aceeri"
sponsor = "https://github.com/sponsors/Aceeri"
