name = "Charlotte"
profile-picture = "GitHub"
bio = "Artist and creative coder. Nannou maintainer."
github = "tychedelia"
twitter = "tychedelia"
instagram = "tychedelia"
website = "https://charlotte.fyi"
