name = "cryscan"
profile-picture = "GitHub"
bio = "Developer of bevy-hikari and bounce-up. Interested in rendering, animation and robotics."
github = "cryscan"
discord = "cryscan#1571"
discord-userid = "618160617580134411"
itch-io = "cryscan"