name = "Jos Feenstra"
bio = "Developer of 3D things. Author of `hedron`: procedural modelling for bevy. Feel free to reach out!"
github = "josfeenstra"
discord = "Feenster#8418"
discord-userid = "364128018656002051"
sponsor = "https://github.com/sponsors/josfeenstra"
profile-picture = "GitHub"
website = "https://josfeenstra.nl"
