name = "Josiah Mbao"
profile-picture = "GitHub"
bio = "Exploring Rust, Bevy, and AI from Kenya. I like building systems that mix creativity with performance."
github = "josiah-mbao"
website = "https://github.com/josiah-mbao"
