name = "Josiah Mbao"
profile-picture = "GitHub"
bio = "Exploring Rust, Bevy, and AI from Kenya. I like building systems that mix creativity with performance.."
github = "josiah-mbao"
website = "https://app.readytensor.ai/publications/ona-vision-real-time-object-detection-monitoring-with-yolov8-deepsort-and-kubernetes-T61kJcd6krI2"
