name = "Kamil Konefke"
profile-picture = "GitHub"
bio = "Game developer and digital artist also a big fan of Formula 1. ❤️"
sponsor = "https://ko-fi.com/kamiidev"
github = "kamilkonefke"
discord = "Kamii#9110"
discord-userid = "432946657362182146"
twitter = "kamilkonefke"
itch-io = "kamiidev"