name = "Pascal Hertleif"
profile-picture = "GitHub"
bio = "Rust developer interested in type systems, neat APIs, and thus obvious follower of the bevy project"

github = "killercup"
discord = "killercup#9050"
mastodon = "@killercup@mastodon.social"
itch-io = "killercup"
website = "https://deterministic.space/"
