name = "Linwei Zhang"
profile-picture = "GitHub"
bio = "Build games for fun"
github = "lewiszlw"
discord = "linwei#8522"
discord-userid = "891664307035713576"
mastodon = "@lewiszlw@mastodon.world"
twitter = "lewiszlw"
itch-io = "lewiszlw"
website = "https://nightswatch.games"
