name = "Piotr Siuszko"
profile-picture = "GitHub"
bio = "Rust and Bevy enthusiast, Developer of tools for Unity, maintainer of a few bevy plugin crates."

github = "leinnan"
discord = "mevlyshkin"
mastodon = "@MevLyshkin@mastodon.gamedev.place"
itch-io = "mevlyshkin"
website = "https://www.mevlyshkin.com/"
