name = "Luke Yoo"
profile-picture = "GitHub"
bio = "Software engineer, passionate about real-time systems, graphics programming, and building innovative tools with Bevy."
github = "micttyoid"
discord = "micttyoid"
twitter = "micttyoid"
