name = "Paul Hansen"
bio = "Slayer of Windows bugs. Currently working on an unannounced 2d space RPG using Bevy in my free time. Happy to help where I can."
github = "paul-hansen"
itch-io = "prawl"
discord = "PaulH#7052"
discord-userid = "223122443332485123"
mastodon = "@paul@mastodon.gamedev.place"
sponsor = "https://github.com/sponsors/paul-hansen"
profile-picture = "GitHub"
