name = "Rob Macdonald"
bio = "rust, python, maths, rendering, games"
github = "robtfm"
discord = "robtfm#2240"
discord-userid = "robtfm"
mastodon = "@robtfm@toot.community"
twitter = "robtfm"
itch-io = "robtfm"
