name = "Ruslan"
profile-picture = "GitHub"
bio = "Fullstack developer and SEO enthusiast. I'm collecting browser games on my website."
sponsor = "https://ko-fi.com/ruslanrocks"
github = "rusya13"
discord = "ruslan.rocks"
discord-userid = "121339919212871680"
twitter = "rusya13"
website = "https://ruslan.rocks"
