name = "Piotr Kosek"
profile-picture = "GitHub"
bio = "An IT passionate and veteran, legends says his very first video game was conceived in former millennium (it was a PowerPoint game book in 1999 actually)"
# sponsor = ""
github = "Shelim"
discord = "piotr_kosek"
discord-userid = "335800721205100545"
# mastodon = "@username@instance.com"
# twitter = "username"
itch-io = "shelim"
# steam-developer = "developer_name"
website = "https://piotr.kosek.com"
