name = "therabug"
profile-picture = "GitHub"

bio = "Just into games, game engines, and having a good time! :)"

github = "therabug"

discord = "therabug"
discord-userid = "541194606214250496"

mastodon = "@rabug@mastodon.social"

twitter = "TheRabug"

itch-io = "rabug50"

website = "https://rabug.is-a.dev"
