name = "Michael Van Der Velden"
profile-picture = "GitHub"
bio = "I'm an Engineering Leader with over 9 years of commercial software development experience, mainly on the backend of web development. I work with rust and bevy in my free time. One day I may even release something!"
sponsor = "https://github.com/sponsors/vandie"
github = "vandie"
discord = "codereview"
discord-userid = "112109342647398400"
itch-io = "mikevdev"
website = "https://mikevdv.dev"
