name = "Anselmo Sampietro"
profile-picture = "GitHub"
bio = "Solo dev behind Times of Progress, a Bevy game on Steam."
github = "wilk10"
discord = "elmo4899"
discord-userid = "744542434293186660"
mastodon = "@elmowilk@mastodon.online" 
twitter = "ElmoSampedro"
steam-developer = "pressingthumbs"
website = "https://www.pressingthumbs.com/about/"
