name = "Alice Cecile"
bio = "Technical project manager, mad scientist, and documentation lead. Loves tinkering with ECS features."
github = "alice-i-cecile"
itch-io = "leafwing-studios"
discord = "IvyLashes#9571"
discord-userid = "159873981174906880"
mastodon = "@alice_i_cecile@tech.lgbt"
sponsor = "https://github.com/sponsors/alice-i-cecile"
profile-picture = "GitHub"
