name = "François"
github = "mockersf"
itch-io = "vleue"
discord = "François#2474"
mastodon = "@FrancoisMockers@hachyderm.io"
sponsor = "https://github.com/sponsors/mockersf"
profile-picture = "GitHub"
