name = "François Mockers"
bio = "Helping everything run smoothly, and having fun with Bevy!"
github = "mockersf"
itch-io = "vleue"
discord = "François#2474"
discord-userid = "456733500280930306"
mastodon = "@FrancoisMockers@hachyderm.io"
sponsor = "https://github.com/sponsors/mockersf"
profile-picture = "GitHub"
