name = "Aevyrie Roessler"
profile-picture = "GitHub"
bio = "Formerly a Mechanical Engineer, now building CAD software in Bevy. I maintain a number of 3rd-party Bevy crates. Feel free to reach out and say hello!"
github = "aevyrie"
discord = "haev#6205"
