name = "Jerome Humbert"
profile-picture = "GitHub"
bio = "Maintainer for 🎆 Hanabi, the best (and only) GPU particle plugin for Bevy, and a few other plugins. Occasional contributions and reviews to Bevy itself."
github = "djeedai"
discord = "djee#0232"
mastodon = "@djee@mastodon.gamedev.place"
twitter = "djeedai"
itch-io = "djee"
