name = "harudagondi"
profile-picture = "./harudagondi.svg"
bio = "Chemistry enthusiast, interested in audio and music stuff."
sponsor = "https://ko-fi.com/harudagondi"
github = "harudagondi"
discord = "harudagondi#1480"
discord-userid = "599833361565089802"
mastodon = "@harudagondi@tech.lgbt"
twitter = "harudagondi"
itch-io = "harudagondi"
website = "https://harudagondi.vercel.app/"