name = "Mike Hsu"
profile-picture = "GitHub"
bio = "Lapsed physics major finding refuge in the programming world for going on 20 years. Mostly been focused on messing with the scheduler and task pool for my work on bevy."
github = "hymm"
discord = "WrongShoe#9733"
discord-userid = "92843110211534848"
itch-io = "MyWrongShoe"
website = "https://hsubox.design"
