name = "Ida \"Iyes\""
profile-picture = "GitHub"
bio = "Likes to teach and explain things. Talks a lot (sometimes with her cat). Makes games, sometimes music and other creative things. Community is Love. Ice is Win. 👀"
sponsor = "https://github.com/sponsors/inodentry"
github = "inodentry"
discord = "Ida Iyes#0981"
discord-userid = "574293018249527308"
mastodon = "@iyes@mastodon.gamedev.place"
twitter = "@IyesGames"
itch-io = "iyes"
website = "https://iyes.games"
