name = "Joseph Giordano"
profile-picture = "GitHub"
bio = "Software engineer and open source enthusiast using Bevy professionally. Author of the crate 'bevy-trait-query'."
github = "JoJoJet"
discord = "JoJoJet#9044"
