name = "Joseph Giordano"
profile-picture = "GitHub"
bio = "Undergrad computer science student, open source enthusiast, and hobbyist game developer. Author of the crate 'bevy-trait-query'."
github = "JoJoJet"
discord = "JoJoJet#9044"
