name = "Joona Aalto"
bio = "Maintainer of the Avian physics engine for Bevy. Working on shiny simulations and math, breathing life into creations."
github = "Jondolf"
discord = "Jondolf#7830"
discord-userid = "545959292281552928"
mastodon = "@Jondolf@mastodon.social"
website = "https://joonaa.dev"
sponsor = "https://github.com/sponsors/Jondolf"
profile-picture = "GitHub"
