name = "Kurt Kühnert"
bio = "German master's student specializing in computer graphics. Author of bevy_terrain. Focused on improving the ergonomics and documentation of Bevy's renderer."
github = "kurtkuehnert"
discord = "kurtkuehnert#8689"
sponsor = "https://github.com/sponsors/kurtkuehnert"
profile-picture = "GitHub"
website = "https://github.com/kurtkuehnert/bevy_terrain"
