name = "Joy"
bio = "I keep getting tricked into working on the ECS, but I'm also invested in improving the plugin system, input handling, and general UX."
github = "maniwani"
discord = "Joy#1194"
discord-userid = "143102494849892352"
profile-picture = "GitHub"