name = "Nicola Papale"
bio = "Making games at devildahu. Author of bevy-ui-navigation, cuicui and many other bevy-related crates. Incidentally contributes to bevy. Touches reflection, rendering, ui and ecs."
itch-io = "gibonus"
github = "nicopap"
sponsor = "https://github.com/sponsors/nicopap"
profile-picture = "GitHub"
website = "https://nicopap.ch/"
