name = "Niklas Eicker"
profile-picture = "GitHub"
bio = "Maintainer of some 3rd-party plugins. Likes joining game jams using Bevy."
github = "NiklasEi"
discord = "Nikl#6226"
discord-userid = "170873850559594506"
mastodon = "@nikl_me@mastodon.online"
twitter = "nikl_me"
itch-io = "niklme"
website = "https://nikl.me"
