name = "soqb"
profile-picture = "GitHub"
bio = "rust-lang & bevy fanatic who lurks in the twilight, at the threshold of the invisible. perchance."
github = "soqb"
discord = "radiish#9483"
discord-userid = "656215839921405982"
mastodon = "@soqb@mstdn.social"
