name = "Rob Swain"
bio = "Wielder of light. Turning data into shiny. I love to discuss ideas and help people figure out how to do stuff, or to find other people who can help - please ask me questions! ❤️"
github = "superdump"
discord = "robswain#0382"
discord-userid = "306495754187440132"
twitter = "swainrob"
mastodon = "@swainrob@mastodon.gamedev.place"
profile-picture = "GitHub"
itch-io = "robswain"
