name = "Nile"
profile-picture = "GitHub"
bio = "Formerly active member of the community, and still the uncontested owner of the highest message count on the bevy discord. I will one day return to the forefront of mad science! 🧪"
sponsor = "https://www.buymeacoffee.com/therawmeatball"
github = "TheRawMeatball"
discord = "NileTheRawMeatball#3001"
discord-userid = "408651609887735809"
