name = "charlotte 🌸"
profile-picture = "GitHub"
bio = "Artist and creative coder. Nannou maintainer."
github = "tychedelia"
instagram = "___whorl"
bluesky = "charlotte.fyi"
website = "https://charlotte.fyi"
