name = "Talin"
profile-picture = "GitHub"
github = "viridia"
discord = "dreamertalin"
discord-userid = "301060831314182146"
mastodon = "@dreamertalin@mastodon.social"
bio = "Recovering game programmer and mad natural philosopher. Published several games on the Commodore Amiga in the 1980s. Worked on Sim City 4 and Sims 2."
