name = "VitalyR, Vitaly Ankh"
profile-picture = "GitHub"
bio = "Programmer and mathematics learner. Interested in programming language theory, algebraic topology, computer graphics and computer architeture."
github = "VitalyAnkh"
discord = "VitalyR#7765"
discord-userid = "405339097427869697"
mastodon = "@vitalyr@types.pl"
website = "https://vitalyr.com"
