name = "Thierry Berger"
bio = "Helping one project after the other, fixing papercuts along the way. Tell me about yours!"
github = "vrixyz"
itch-io = "vrixyz"
discord = "ThierryBerger#8164"
discord-userid = "115104896969080833"
mastodon = "@Vrixyz@mastodon.gamedev.place"
sponsor = "https://github.com/sponsors/vrixyz"
profile-picture = "GitHub"
