# Name you want to appear with. This can be whatever name/alias makes you most comfortable.
# Mandatory
name = "Nathan Stocks"

# File name of your profile picture if you uploaded one
# If you provide a file, be mindful of its size
# If you also add your github profile, you can use "GitHub" to use your GitHub profile picture
# This can be any image that follows our code of conduct.
# Optional
profile-picture = "GitHub"

# Short presentation of yourself. This has a limit of 180 characters.
# Optional
bio = "Indie Game Dev, Rust Instructor, Rusty Engine creator. Senior Software Engineer at GitHub. Family, Food, Rust, Python, Open Source, Maple Trees."

# Link to your sponsoring page, GitHub Sponsor, Patreon, Buy Me a Coffee, ...
# Optional
sponsor = "https://github.com/sponsors/CleanCut"

# Social links

# Will link to https://github.com/<username>
# Optional
github = "CleanCut"

discord = "DiscordUsername#1234"
# This allows direct linking to your profile for people with a shared server
# https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
# Optional
discord-userid = ""

## Will link to https://<instance.com>/@<username>
# Optional
mastodon = "@nathanstocks@hachyderm.io"

## Will link to https://twitter.com/<username>
# Optional
twitter = "nathanstocks"

## Will link to https://<username>.itch.io/
# Optional
itch-io = "cleancut"

## Will link to http://store.steampowered.com/developer/<developer_name>
# Optional
#steam-developer = "developer_name"

## Free link, will be displayed as is
# Optional
website = "https://agileperception.com/"
