name = "Jakob Hellermann"
profile-picture = "GitHub"
bio = "Currently switching between editor tooling, graphics and scripting. Otherwise interested in music, nature, and figuring stuff out."
github = "jakobhellermann"
discord = "dubi steinkek#2182"
discord-userid = "305422711256252416"