name = "Joy"
bio = "Focused on general engine UX, plugin interop, input handling, and multiplayer. Keeps getting tricked into working on the ECS."
github = "maniwani"
discord = "Joy#1194"
discord-userid = "143102494849892352"
profile-picture = "GitHub"