name = "Gino Valente"
profile-picture = "GitHub"
bio = "React Native developer during the day, Bevy contributor at night. Focused mainly on Bevy's reflection system."
sponsor = "https://github.com/sponsors/MrGVSV"
github = "MrGVSV"
discord = "MrGVSV#7930"
discord-userid = "583870588943335427"
twitter = "https://twitter.com/TheGinoValente"
itch-io = "https://mrgvsv.itch.io/"
website = "https://ginovalente.me"